GET http://172.31.2.55/api/registrations

###
GET http://172.31.2.55/api/registrations/a14424c7-b763-4dd8-743e-d87d4107bc79

###
POST http://172.31.2.55/api/registrations
Content-Type: application/json

{
	"user": {
		"firstName": "Volt4",
		"lastName": "Troll4",
		"email": "ramp@example.com",
		"skills": ["c#", "go", "NodeJS"],
        "equipment": "ncci"
	},
	"team": {
		"name": "Horizon",
		"logo": "http://example.com/logo.jpg",
		"members": ["John", "Yohay", "Jeff"]
	},
	"idea": {
		"title": "Idea 2",
		"description": "Another idea that will be better"
	}
}

###
DELETE http://172.31.2.55/api/registrations/1fb658a4-d319-4b23-6f4b-08b02bd7ffc4
