GET http://localhost:8080/api/registrations

###
GET http://localhost:8080/api/registrations/1

###
POST http://localhost:8080/api/registrations
Content-Type: application/json

{
	"user": {
		"firstName": "Ismail",
		"lastName": "Fletcher",
		"email": "ifletcher@example.com",
		"skills": ["c#", "go", "NodeJS"]
	},
	"team": {
		"name": "Horizon",
		"logo": "http://example.com/logo.jpg",
		"members": ["John", "Yohay", "Jeff"]
	},
	"idea": {
		"title": "Idea 2",
		"description": "Another idea that will be better"
	}
}

###
DELETE http://localhost:8080/api/registrations/48e24ddb-8dfa-4b03-7bb1-a7dd10d75ec2