GET http://localhost:8080/api/registrations

###
GET http://localhost:8080/api/registrations/1

###
POST http://localhost:8080/api/registrations
Content-Type: application/json

{
	"id": "3",
	"title": "Sample Idea 3",
	"description": "A simple idea to test application 2",
	"path": ""
}

###
DELETE http://localhost:8080/api/registrations/1